# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0
name: OpenSSF Scorecard Analysis
on:
  schedule:
    # Saturdays at 02:15 UTC
    - cron: "15 2 * * 6"
    # Wednesdays at 02:15 UTC
    - cron: "15 2 * * 3"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  scorecard-analysis:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: diggsweden/reusable-ci/.github/workflows/security-openssf-scorecard.yml@e29145e720cef0b86ef147c72c2d001b5ac6c8b9 # v2.4.2
    with:
      publish-results: true
